services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: feri
      POSTGRES_PASSWORD: feri
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rferko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: feri
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
  webapi:
    image: rferko/diszkerteszapi:1.4
    restart: always
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=diszkertesz;Username=feri;Password=feri"
    volumes:
      - /etc/diszkertesz_images:/app/images

volumes:
  pgdata:
  pgadmin-data:
